language: php
php:
  - '7.0'
  - '7.1'
install:
  - composer install
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p tests/output/report
  - composer test
after_script:
  - php vendor/bin/coveralls -v
notifications:
  email:
    recipients: VDVUGaD@gmail.com
    on_success: change
    on_failure: always
